# Generated by Django 5.0.7 on 2024-07-11 13:46

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('christmas_party', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PH'),
        ),
    ]
