# Generated by Django 5.0.7 on 2024-07-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmas_party', '0002_alter_attendance_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
