# Generated by Django 5.0.7 on 2024-07-12 14:03

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('christmas_party', '0003_alter_attendance_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter your Contact Number (eg: 0912345679)', max_length=128, region='PH'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='full_name',
            field=models.CharField(help_text='Enter your Full name', max_length=255),
        ),
    ]
